repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.4.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - post-commit
          - pre-push
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.2.0
    hooks:
      - id: editorconfig-checker
        args: [-disable-indent-size]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies:
          - sphinx
          - types-setuptools
          - types-toml
          - typing_extensions
        exclude: tests/
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.6
    hooks:
      - id: uv-lock
      - id: uv-export
        args: ["-o", "requirements.txt"]
      - id: uv-export
        args: ["--group", "docs", "-o", "docs/requirements.txt"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [markdown, yaml]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
