"""This type stub file was generated by pyright."""

from typing import List, NamedTuple, Union

from cocotb.triggers import Event

from .address_space import Region
from .constants import AxiBurstType, AxiLockType, AxiProt, AxiResp
from .reset import Reset

"""

Copyright (c) 2020 Alex Forencich

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

"""

class AxiWriteCmd(NamedTuple):
    address: int
    data: bytes
    awid: int
    burst: AxiBurstType
    size: int
    lock: AxiLockType
    cache: int
    prot: AxiProt
    qos: int
    region: int
    user: int
    wuser: Union[list, int, None]
    event: Event
    ...

class AxiWriteRespCmd(NamedTuple):
    address: int
    length: int
    size: int
    cycles: int
    prot: AxiProt
    burst_list: List[int]
    event: Event
    ...

class AxiWriteResp(NamedTuple):
    address: int
    length: int
    resp: AxiResp
    user: Union[list, None]
    ...

class AxiReadCmd(NamedTuple):
    address: int
    length: int
    arid: int
    burst: AxiBurstType
    size: int
    lock: AxiLockType
    cache: int
    prot: AxiProt
    qos: int
    region: int
    user: int
    event: Event
    ...

class AxiReadRespCmd(NamedTuple):
    address: int
    length: int
    size: int
    cycles: int
    prot: AxiProt
    burst_list: List[int]
    event: Event
    ...

class AxiReadResp(NamedTuple):
    address: int
    data: bytes
    resp: AxiResp
    user: Union[list, None]
    def __bytes__(self):  # -> bytes:
        ...

class TagContext:
    def __init__(self, manager) -> None: ...
    async def get_resp(self): ...
    def get_resp_nowait(self): ...

class TagContextManager:
    def __init__(self, process) -> None: ...
    def start_cmd(self, tag, cmd):  # -> None:
        ...
    def put_resp(self, tag, resp):  # -> None:
        ...
    def flush(self):  # -> list[Any]:
        ...

class AxiMasterWrite(Region, Reset):
    def __init__(
        self,
        bus,
        clock,
        reset=...,
        reset_active_level=...,
        max_burst_len=...,
        **kwargs,
    ) -> None: ...
    def init_write(
        self,
        address,
        data,
        awid=...,
        burst=...,
        size=...,
        lock=...,
        cache=...,
        prot=...,
        qos=...,
        region=...,
        user=...,
        wuser=...,
        event=...,
    ):  # -> Event:
        ...
    def idle(self):  # -> bool:
        ...
    async def wait(self):  # -> None:
        ...
    async def write(
        self,
        address,
        data,
        awid=...,
        burst=...,
        size=...,
        lock=...,
        cache=...,
        prot=...,
        qos=...,
        region=...,
        user=...,
        wuser=...,
    ): ...

class AxiMasterRead(Region, Reset):
    def __init__(
        self,
        bus,
        clock,
        reset=...,
        reset_active_level=...,
        max_burst_len=...,
        **kwargs,
    ) -> None: ...
    def init_read(
        self,
        address,
        length,
        arid=...,
        burst=...,
        size=...,
        lock=...,
        cache=...,
        prot=...,
        qos=...,
        region=...,
        user=...,
        event=...,
    ):  # -> Event:
        ...
    def idle(self):  # -> bool:
        ...
    async def wait(self):  # -> None:
        ...
    async def read(
        self,
        address,
        length,
        arid=...,
        burst=...,
        size=...,
        lock=...,
        cache=...,
        prot=...,
        qos=...,
        region=...,
        user=...,
    ): ...

class AxiMaster(Region):
    def __init__(
        self,
        bus,
        clock,
        reset=...,
        reset_active_level=...,
        max_burst_len=...,
        **kwargs,
    ) -> None: ...
    def init_read(
        self,
        address,
        length,
        arid=...,
        burst=...,
        size=...,
        lock=...,
        cache=...,
        prot=...,
        qos=...,
        region=...,
        user=...,
        event=...,
    ):  # -> Event:
        ...
    def init_write(
        self,
        address,
        data,
        awid=...,
        burst=...,
        size=...,
        lock=...,
        cache=...,
        prot=...,
        qos=...,
        region=...,
        user=...,
        wuser=...,
        event=...,
    ):  # -> Event:
        ...
    def idle(self):  # -> bool:
        ...
    async def wait(self):  # -> None:
        ...
    async def wait_read(self):  # -> None:
        ...
    async def wait_write(self):  # -> None:
        ...
    async def read(
        self,
        address,
        length,
        arid=...,
        burst=...,
        size=...,
        lock=...,
        cache=...,
        prot=...,
        qos=...,
        region=...,
        user=...,
    ): ...
    async def write(
        self,
        address,
        data,
        awid=...,
        burst=...,
        size=...,
        lock=...,
        cache=...,
        prot=...,
        qos=...,
        region=...,
        user=...,
        wuser=...,
    ): ...
