"""This type stub file was generated by pyright."""

from typing import Callable, Type, TypeVar

AnyCallableT = TypeVar("AnyCallableT", bound=Callable[..., object])

def deprecated(
    msg: str, category: Type[Warning] = ...
) -> Callable[[AnyCallableT], AnyCallableT]:
    """Emits a DeprecationWarning when the decorated function is called.

    This decorator works on normal functions, methods, and properties.
    Usage on properties requires the ``@property`` decorator to appear outside the
    ``@deprecated`` decorator.
    Concrete classes can be deprecated by decorating their ``__init__`` or ``__new__``
    method.

    Args:
        msg: the deprecation message
        category: the warning class to use
    """
    ...
