"""This type stub file was generated by pyright."""

import argparse

"""
Module for querying the cocotb configuration

This module provides information in module global variables and through a
``main()`` function that is used in the cocotb-config script.

Global variables:
    share_dir: str, path where the cocotb data is stored
    makefiles_dir: str, path where the cocotb makefiles are installed
    libs_dir: str, path where the cocotb interface libraries are located
"""
__all__ = ["libs_dir", "makefiles_dir", "share_dir"]
base_dir = ...
share_dir = ...
makefiles_dir = ...
libs_dir = ...

def help_vars_text():  # -> str:
    ...
def lib_name(interface: str, simulator: str) -> str:
    """Return the name of interface library for given interface (VPI/VHPI/FLI) and simulator."""
    ...

def lib_name_path(interface, simulator):  # -> str:
    """Return the absolute path of interface library for given interface (VPI/VHPI/FLI) and simulator"""
    ...

class PrintAction(argparse.Action):
    def __init__(self, option_strings, dest, text=..., **kwargs) -> None: ...
    def __call__(self, parser, namespace, values, option_string=...): ...

class PrintFuncAction(argparse.Action):
    def __init__(
        self, option_strings, dest, function=..., **kwargs
    ) -> None: ...
    def __call__(self, parser, args, values, option_string=...):  # -> None:
        ...

def get_parser():  # -> ArgumentParser:
    ...
def main():  # -> None:
    ...

if __name__ == "__main__": ...
