"""This type stub file was generated by pyright."""

import typing

def concat(a: typing.Any, b: typing.Any) -> typing.Any:
    """Create a new array that is the concatenation of one array with another.

    Uses the :meth:`__concat__` or :meth:`__rconcat__` special methods to dispatch to a particular implementation,
    exactly like other binary operations in Python.

    Raises:
        TypeError: when the arguments do not support concatenation in the given order.
    """
    ...
