name: Check
on:
  push:
    branches-ignore: ["gh-pages"]
  pull_request:
jobs:
  run:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Assert PR target is main
        if: github.event_name == 'pull_request' && github.repository == 'InES-HPMM/cocotb-wrapper'
        run: |
          if [ "$GITHUB_BASE_REF" != "main" ]; then
            echo "::error::PR targeting '$GITHUB_BASE_REF', please refile targeting 'main'." && exit 1
          fi
      - name: Set up latest Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade uv
          uv sync --group dev --group docs
      - name: Check types
        run: uv run basedpyright --level error
      - name: Lint files
        run: uv run ruff check
      - name: Format files
        run: uv run ruff format
