name: Documentation
on:
  push:
    branches-ignore: ["gh-pages"]
  pull_request:
jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up latest Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade poetry
          poetry install --with docs
      - name: Build documentation
        run: poetry run sphinx-build -a -b html docs/ docs/_build
