name: Publish to Pages
on:
  push:
    branches: [main]
jobs:
  pages:
    runs-on: self-hosted
    steps:
      - id: deployment
        uses: sphinx-notes/pages@v3
        with:
          publish: false
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ steps.deployment.outputs.artifact }}
